-- Tours
INSERT INTO "Tour" (price, location, "isActive", "createdAt", "updatedAt")
VALUES 
(1200, 'Cozumel', true, NOW(), NOW()),
(1500, 'Cancún', true, NOW(), NOW()),
(1800, 'Cancún', true, NOW(), NOW()),
(1300, 'Cancún', true, NOW(), NOW()),
(1600, 'Cancún', true, NOW(), NOW()),
(3500, 'Cancún', true, NOW(), NOW()),
(4500, 'Riviera Maya', true, NOW(), NOW()),
(4200, 'Riviera Maya', true, NOW(), NOW()),
(4300, 'Riviera Maya', true, NOW(), NOW()),
(4600, 'Riviera Maya', true, NOW(), NOW()),
(3200, 'Riviera Maya', true, NOW(), NOW()),
(2500, 'Yucatán', true, NOW(), NOW()),
(2200, 'Quintana Roo', true, NOW(), NOW()),
(2100, 'Quintana Roo', true, NOW(), NOW()),
(2300, 'Yucatán', true, NOW(), NOW()),
(2400, 'Yucatán', true, NOW(), NOW()),
(1800, 'Quintana Roo', true, NOW(), NOW()),
(2000, 'Quintana Roo', true, NOW(), NOW()),
(2300, 'Quintana Roo', true, NOW(), NOW()),
(1900, 'Quintana Roo', true, NOW(), NOW()),
(2200, 'Quintana Roo', true, NOW(), NOW()),
(1700, 'Quintana Roo', true, NOW(), NOW()),
(2600, 'Quintana Roo', true, NOW(), NOW()),
(1900, 'Quintana Roo', true, NOW(), NOW()),
(2800, 'Yucatán', true, NOW(), NOW()),
(1800, 'Quintana Roo', true, NOW(), NOW()),
(4200, 'Quintana Roo', true, NOW(), NOW()),
(1500, 'Quintana Roo', true, NOW(), NOW()),
(1900, 'Quintana Roo', true, NOW(), NOW()),
(3500, 'Quintana Roo', true, NOW(), NOW()),
(2200, 'Quintana Roo', true, NOW(), NOW()),
(2600, 'Quintana Roo', true, NOW(), NOW()),
(3000, 'Quintana Roo', true, NOW(), NOW()),
(2800, 'Quintana Roo', true, NOW(), NOW()),
(2500, 'Quintana Roo', true, NOW(), NOW()),
(3200, 'Quintana Roo', true, NOW(), NOW()),
(4200, 'Quintana Roo', true, NOW(), NOW()),
(2300, 'Quintana Roo', true, NOW(), NOW()),
(2000, 'Quintana Roo', true, NOW(), NOW());

-- Tour Translations (Español)
INSERT INTO "TourTranslation" (language, title, description, category, duration, "tourId")
VALUES 
('es', 'Snorkel & Buceo', 'Explora arrecifes cristalinos y vive la experiencia de nadar entre peces tropicales.', 'Acuaticos', '4 horas', 1),
('es', 'Motos Acuáticas', 'Siente la adrenalina recorriendo el mar a toda velocidad en motos acuáticas.', 'Aventura', '30 minutos', 2),
('es', 'Speed Boats', 'Recorre canales y mar abierto a gran velocidad mientras conduces tu propio speed boat.', 'Acuaticos', '1 hora', 3),
('es', 'Parasailing', 'Disfruta vistas espectaculares del mar mientras vuelas sobre el agua en una experiencia inolvidable.', 'Acuaticos', '15 minutos', 4),
('es', 'Catamaran', 'Navega en catamarán y disfruta del mar con música, bebidas y un ambiente relajado.', 'Acuaticos', '4 horas', 5),
('es', 'Yate', 'Vive una experiencia de lujo navegando en yate con comodidad, privacidad y vistas increíbles.', 'Acuaticos', '4 horas', 6),
('es', 'Xcaret', 'Vive un parque eco-arqueológico con ríos subterráneos, espectáculos y cultura mexicana.', 'Parques', 'Todo el día', 7),
('es', 'Xel-Há', 'Disfruta un parque natural todo incluido con snorkel, ríos y naturaleza sin límites.', 'Parques', 'Todo el día', 8),
('es', 'Xplor (Día)', 'Vive una aventura extrema con tirolesas, ríos subterráneos y vehículos anfibios.', 'Parques', 'Todo el día', 9),
('es', 'Xplor Fuego', 'Disfruta Xplor de noche con tirolesas, ríos y aventuras iluminadas por antorchas.', 'Parques', 'Tarde - Noche', 10),
('es', 'Xenses', 'Un parque sensorial que desafía tus sentidos con experiencias únicas y sorprendentes.', 'Parques', 'Medio día', 11),
('es', 'Chichén Itzá', 'Visita una de las siete maravillas del mundo y descubre la grandeza de la civilización maya.', 'Arqueologicos', 'Todo el día', 12),
('es', 'Tulum', 'Explora las ruinas mayas frente al mar Caribe con vistas espectaculares.', 'Arqueologicos', 'Todo el día', 13),
('es', 'Cobá', 'Recorre antiguas ruinas mayas rodeadas de selva y pirámides imponentes.', 'Arqueologicos', 'Todo el día', 14),
('es', 'Ek Balam', 'Descubre una zona arqueológica maya con impresionantes esculturas y arquitectura.', 'Arqueologicos', 'Todo el día', 15),
('es', 'Uxmal', 'Admira una joya del mundo maya famosa por su arquitectura y detalles únicos.', 'Arqueologicos', 'Todo el día', 16),
('es', 'Tirolesas', 'Vuela sobre la selva en un emocionante recorrido lleno de adrenalina.', 'Extremos y Aventura', 'Medio día', 17),
('es', 'ATV', 'Conduce cuatrimotos a través de caminos selváticos y terrenos extremos.', 'Extremos y Aventura', 'Medio día', 18),
('es', 'Razer', 'Vive una aventura off-road manejando vehículos todo terreno de alta potencia.', 'Extremos y Aventura', 'Medio día', 19),
('es', 'Rappel', 'Desciende por paredes naturales y siente la emoción del rappel en la selva.', 'Extremos y Aventura', 'Medio día', 20),
('es', 'Buggy', 'Explora senderos salvajes en buggy y disfruta una experiencia llena de acción.', 'Extremos y Aventura', 'Medio día', 21),
('es', 'Cenotes', 'Nada en cenotes de aguas cristalinas rodeados de naturaleza y tranquilidad.', 'Naturaleza', 'Medio día', 22),
('es', 'Bacalar', 'Descubre la Laguna de los Siete Colores y disfruta un paraíso natural único.', 'Naturaleza', 'Todo el día', 23),
('es', 'Lagunas', 'Explora hermosas lagunas naturales y relájate en entornos paradisíacos.', 'Naturaleza', 'Medio día', 24),
('es', 'Río Lagartos', 'Admira flamencos, manglares y paisajes únicos en una reserva natural protegida.', 'Naturaleza', 'Todo el día', 25),
('es', 'Nado con Tortugas', 'Nada junto a tortugas marinas en su hábitat natural.', 'Vida Silvestre', 'Medio día', 26),
('es', 'Nado con Tiburón Ballena', 'Vive una experiencia única nadando con el pez más grande del mundo.', 'Vida Silvestre', 'Todo el día', 27),
('es', 'Paseo a Caballo', 'Disfruta un tranquilo paseo a caballo rodeado de naturaleza.', 'Vida Silvestre', 'Medio día', 28),
('es', 'Paseo en Camello', 'Una experiencia diferente y exótica con paseo en camello.', 'Vida Silvestre', 'Medio día', 29),
('es', 'Nado con Delfines', 'Interactúa y nada con delfines en una experiencia inolvidable.', 'Vida Silvestre', 'Medio día', 30),
('es', 'Isla Mujeres', 'Disfruta playas de arena blanca y aguas cristalinas en una isla paradisíaca.', 'Islas', 'Todo el día', 31),
('es', 'Isla Cozumel', 'Explora una isla famosa por su arrecife, playas y ambiente relajado.', 'Islas', 'Todo el día', 32),
('es', 'Isla Contoy', 'Visita una reserva natural protegida con playas vírgenes y fauna única.', 'Islas', 'Todo el día', 33),
('es', 'Isla Holbox', 'Descubre una isla bohemia con playas tranquilas y paisajes inolvidables.', 'Islas', 'Todo el día', 34),
('es', 'Coco Bongo', 'Vive el show nocturno más famoso de Cancún con música, acrobacias y fiesta.', 'Entretenimiento Nocturno', 'Noche', 35),
('es', 'Xochimilco', 'Fiesta mexicana con música en vivo, comida típica y ambiente festivo.', 'Entretenimiento Nocturno', 'Noche', 36),
('es', 'Joya Cirque du Soleil', 'Espectáculo impresionante que combina acrobacias, teatro y gastronomía.', 'Entretenimiento Nocturno', 'Noche', 37),
('es', 'Barco Pirata', 'Show familiar con piratas, música y diversión en altamar.', 'Entretenimiento Nocturno', 'Noche', 38),
('es', 'Night Clubs', 'Acceso a los mejores antros y clubs nocturnos de la zona.', 'Entretenimiento Nocturno', 'Noche', 39);

-- Tour Translations (English)
INSERT INTO "TourTranslation" (language, title, description, category, duration, "tourId")
VALUES 
('en', 'Snorkel & Diving', 'Explore crystal clear reefs and experience swimming among tropical fish.', 'Aquatic', '4 hours', 1),
('en', 'Jet Skis', 'Feel the adrenaline racing across the sea at full speed on jet skis.', 'Adventure', '30 minutes', 2),
('en', 'Speed Boats', 'Navigate channels and open sea at high speed while driving your own speed boat.', 'Aquatic', '1 hour', 3),
('en', 'Parasailing', 'Enjoy spectacular views of the sea while flying over the water in an unforgettable experience.', 'Aquatic', '15 minutes', 4),
('en', 'Catamaran', 'Sail on a catamaran and enjoy the sea with music, drinks and a relaxed atmosphere.', 'Aquatic', '4 hours', 5),
('en', 'Yacht', 'Experience luxury sailing on a yacht with comfort, privacy and incredible views.', 'Aquatic', '4 hours', 6),
('en', 'Xcaret', 'Experience an eco-archaeological park with underground rivers, shows and Mexican culture.', 'Parks', 'All day', 7),
('en', 'Xel-Há', 'Enjoy an all-inclusive natural park with snorkeling, rivers and unlimited nature.', 'Parks', 'All day', 8),
('en', 'Xplor (Day)', 'Experience extreme adventure with ziplines, underground rivers and amphibious vehicles.', 'Parks', 'All day', 9),
('en', 'Xplor Fire', 'Enjoy Xplor at night with ziplines, rivers and adventures illuminated by torches.', 'Parks', 'Evening - Night', 10),
('en', 'Xenses', 'A sensory park that challenges your senses with unique and surprising experiences.', 'Parks', 'Half day', 11),
('en', 'Chichén Itzá', 'Visit one of the seven wonders of the world and discover the greatness of the Mayan civilization.', 'Archaeological', 'All day', 12),
('en', 'Tulum', 'Explore Mayan ruins facing the Caribbean Sea with spectacular views.', 'Archaeological', 'All day', 13),
('en', 'Cobá', 'Explore ancient Mayan ruins surrounded by jungle and imposing pyramids.', 'Archaeological', 'All day', 14),
('en', 'Ek Balam', 'Discover a Mayan archaeological zone with impressive sculptures and architecture.', 'Archaeological', 'All day', 15),
('en', 'Uxmal', 'Admire a jewel of the Mayan world famous for its architecture and unique details.', 'Archaeological', 'All day', 16),
('en', 'Ziplines', 'Fly over the jungle on an exciting zipline course full of adrenaline.', 'Extreme & Adventure', 'Half day', 17),
('en', 'ATV', 'Drive quads through jungle paths and extreme terrain.', 'Extreme & Adventure', 'Half day', 18),
('en', 'Razer', 'Experience off-road adventure driving high-powered all-terrain vehicles.', 'Extreme & Adventure', 'Half day', 19),
('en', 'Rappelling', 'Descend natural walls and feel the excitement of rappelling in the jungle.', 'Extreme & Adventure', 'Half day', 20),
('en', 'Buggy', 'Explore wild trails in a buggy and enjoy an action-packed experience.', 'Extreme & Adventure', 'Half day', 21),
('en', 'Cenotes', 'Swim in crystal clear cenotes surrounded by nature and tranquility.', 'Nature', 'Half day', 22),
('en', 'Bacalar', 'Discover the Lagoon of Seven Colors and enjoy a unique natural paradise.', 'Nature', 'All day', 23),
('en', 'Lagoons', 'Explore beautiful natural lagoons and relax in paradise settings.', 'Nature', 'Half day', 24),
('en', 'Río Lagartos', 'Admire flamingos, mangroves and unique landscapes in a protected natural reserve.', 'Nature', 'All day', 25),
('en', 'Swim with Turtles', 'Swim with sea turtles in their natural habitat.', 'Wildlife', 'Half day', 26),
('en', 'Swim with Whale Shark', 'Experience a unique swimming with the biggest fish in the world.', 'Wildlife', 'All day', 27),
('en', 'Horseback Riding', 'Enjoy a peaceful horseback ride surrounded by nature.', 'Wildlife', 'Half day', 28),
('en', 'Camel Ride', 'A different and exotic experience with camel riding.', 'Wildlife', 'Half day', 29),
('en', 'Swim with Dolphins', 'Interact and swim with dolphins in an unforgettable experience.', 'Wildlife', 'Half day', 30),
('en', 'Isla Mujeres', 'Enjoy white sand beaches and crystal clear waters in a paradise island.', 'Islands', 'All day', 31),
('en', 'Isla Cozumel', 'Explore an island famous for its reef, beaches and relaxed atmosphere.', 'Islands', 'All day', 32),
('en', 'Isla Contoy', 'Visit a protected natural reserve with virgin beaches and unique wildlife.', 'Islands', 'All day', 33),
('en', 'Isla Holbox', 'Discover a bohemian island with quiet beaches and unforgettable landscapes.', 'Islands', 'All day', 34),
('en', 'Coco Bongo', 'Experience the most famous night show in Cancún with music, acrobatics and party.', 'Night Entertainment', 'Night', 35),
('en', 'Xochimilco', 'Mexican party with live music, typical food and festive atmosphere.', 'Night Entertainment', 'Night', 36),
('en', 'Joya Cirque du Soleil', 'Impressive show combining acrobatics, theater and gastronomy.', 'Night Entertainment', 'Night', 37),
('en', 'Pirate Ship', 'Family show with pirates, music and fun on the high seas.', 'Night Entertainment', 'Night', 38),
('en', 'Night Clubs', 'Access to the best clubs and nightspots in the area.', 'Night Entertainment', 'Night', 39);
