-- Tour Translations (English)
INSERT INTO "TourTranslation" (language, title, description, category, duration, "tourId")
VALUES 
('en', 'Snorkel & Diving', 'Explore crystal clear reefs and experience swimming among tropical fish.', 'Aquatic', '4 hours', 1),
('en', 'Jet Skis', 'Feel the adrenaline racing across the sea at full speed on jet skis.', 'Adventure', '30 minutes', 2),
('en', 'Speed Boats', 'Navigate channels and open sea at high speed while driving your own speed boat.', 'Aquatic', '1 hour', 3),
('en', 'Parasailing', 'Enjoy spectacular views of the sea while flying over the water in an unforgettable experience.', 'Aquatic', '15 minutes', 4),
('en', 'Catamaran', 'Sail on a catamaran and enjoy the sea with music, drinks and a relaxed atmosphere.', 'Aquatic', '4 hours', 5),
('en', 'Yacht', 'Experience luxury sailing on a yacht with comfort, privacy and incredible views.', 'Aquatic', '4 hours', 6),
('en', 'Xcaret', 'Experience an eco-archaeological park with underground rivers, shows and Mexican culture.', 'Parks', 'All day', 7),
('en', 'Xel-Há', 'Enjoy an all-inclusive natural park with snorkeling, rivers and unlimited nature.', 'Parks', 'All day', 8),
('en', 'Xplor (Day)', 'Experience extreme adventure with ziplines, underground rivers and amphibious vehicles.', 'Parks', 'All day', 9),
('en', 'Xplor Fire', 'Enjoy Xplor at night with ziplines, rivers and adventures illuminated by torches.', 'Parks', 'Evening - Night', 10),
('en', 'Xenses', 'A sensory park that challenges your senses with unique and surprising experiences.', 'Parks', 'Half day', 11),
('en', 'Chichén Itzá', 'Visit one of the seven wonders of the world and discover the greatness of the Mayan civilization.', 'Archaeological', 'All day', 12),
('en', 'Tulum', 'Explore Mayan ruins facing the Caribbean Sea with spectacular views.', 'Archaeological', 'All day', 13),
('en', 'Cobá', 'Explore ancient Mayan ruins surrounded by jungle and imposing pyramids.', 'Archaeological', 'All day', 14),
('en', 'Ek Balam', 'Discover a Mayan archaeological zone with impressive sculptures and architecture.', 'Archaeological', 'All day', 15),
('en', 'Uxmal', 'Admire a jewel of the Mayan world famous for its architecture and unique details.', 'Archaeological', 'All day', 16),
('en', 'Ziplines', 'Fly over the jungle on an exciting zipline course full of adrenaline.', 'Extreme & Adventure', 'Half day', 17),
('en', 'ATV', 'Drive quads through jungle paths and extreme terrain.', 'Extreme & Adventure', 'Half day', 18),
('en', 'Razer', 'Experience off-road adventure driving high-powered all-terrain vehicles.', 'Extreme & Adventure', 'Half day', 19),
('en', 'Rappelling', 'Descend natural walls and feel the excitement of rappelling in the jungle.', 'Extreme & Adventure', 'Half day', 20),
('en', 'Buggy', 'Explore wild trails in a buggy and enjoy an action-packed experience.', 'Extreme & Adventure', 'Half day', 21),
('en', 'Cenotes', 'Swim in crystal clear cenotes surrounded by nature and tranquility.', 'Nature', 'Half day', 22),
('en', 'Bacalar', 'Discover the Lagoon of Seven Colors and enjoy a unique natural paradise.', 'Nature', 'All day', 23),
('en', 'Lagoons', 'Explore beautiful natural lagoons and relax in paradise settings.', 'Nature', 'Half day', 24),
('en', 'Río Lagartos', 'Admire flamingos, mangroves and unique landscapes in a protected natural reserve.', 'Nature', 'All day', 25),
('en', 'Swim with Turtles', 'Swim with sea turtles in their natural habitat.', 'Wildlife', 'Half day', 26),
('en', 'Swim with Whale Shark', 'Experience a unique swimming with the biggest fish in the world.', 'Wildlife', 'All day', 27),
('en', 'Horseback Riding', 'Enjoy a peaceful horseback ride surrounded by nature.', 'Wildlife', 'Half day', 28),
('en', 'Camel Ride', 'A different and exotic experience with camel riding.', 'Wildlife', 'Half day', 29),
('en', 'Swim with Dolphins', 'Interact and swim with dolphins in an unforgettable experience.', 'Wildlife', 'Half day', 30),
('en', 'Isla Mujeres', 'Enjoy white sand beaches and crystal clear waters in a paradise island.', 'Islands', 'All day', 31),
('en', 'Isla Cozumel', 'Explore an island famous for its reef, beaches and relaxed atmosphere.', 'Islands', 'All day', 32),
('en', 'Isla Contoy', 'Visit a protected natural reserve with virgin beaches and unique wildlife.', 'Islands', 'All day', 33),
('en', 'Isla Holbox', 'Discover a bohemian island with quiet beaches and unforgettable landscapes.', 'Islands', 'All day', 34),
('en', 'Coco Bongo', 'Experience the most famous night show in Cancún with music, acrobatics and party.', 'Night Entertainment', 'Night', 35),
('en', 'Xochimilco', 'Mexican party with live music, typical food and festive atmosphere.', 'Night Entertainment', 'Night', 36),
('en', 'Joya Cirque du Soleil', 'Impressive show combining acrobatics, theater and gastronomy.', 'Night Entertainment', 'Night', 37),
('en', 'Pirate Ship', 'Family show with pirates, music and fun on the high seas.', 'Night Entertainment', 'Night', 38),
('en', 'Night Clubs', 'Access to the best clubs and nightspots in the area.', 'Night Entertainment', 'Night', 39)
ON CONFLICT ("tourId", language) DO NOTHING;
